package com.route.test.hungrydemo.model.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.route.test.hungrydemo.model.db.User;
import com.route.test.hungrydemo.model.db_shop.Shop;

import com.route.test.hungrydemo.model.db.UserDao;
import com.route.test.hungrydemo.model.db_shop.ShopDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig shopDaoConfig;

    private final UserDao userDao;
    private final ShopDao shopDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        shopDaoConfig = daoConfigMap.get(ShopDao.class).clone();
        shopDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        shopDao = new ShopDao(shopDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Shop.class, shopDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        shopDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public ShopDao getShopDao() {
        return shopDao;
    }

}
